#!/bin/csh
#Usage: build <version> <release>
#Build ELOG distribution

if ($#argv < 2) then
  echo "Usage: build <version> <release>"
  exit
endif
 
set version = $argv[1]
set release = $argv[2]
set dir = /tmp/elog-$version
set archive = elog-$version-$release.tar.gz

# create temporary directory
rm -Rf $dir
mkdir $dir
mkdir $dir/doc
mkdir $dir/src
mkdir $dir/man
mkdir $dir/contrib
mkdir $dir/themes
mkdir $dir/themes/default
mkdir $dir/themes/default/icons
mkdir $dir/logbooks/
mkdir $dir/logbooks/demo

# checkout files
echo Updating files...
cvs update

# copy files to archive
cp src/*.c $dir/src
cp Makefile $dir
cp elogd.cfg $dir/elogd.cfg
cp COPYING $dir
cp README $dir
cp elogd.init_template $dir

cp eloghelp_??.html $dir
cp eloglang.* $dir

cp doc/* $dir/doc
cp man/* $dir/man
cp contrib/* $dir/contrib

cp themes/default/* $dir/themes/default
cp themes/default/icons/* $dir/themes/default/icons
cp logbooks/demo/* $dir/logbooks/demo

# create elog-x.xx.tar.gz file
echo Creating archive...
cd /tmp
tar -cvzf $archive elog-$version/

# remove temporary files
rm -Rf $dir

# transfer archive
cd /home/midas/elog
cp /tmp/$archive /home/midas/html/elog/download/tar/
cp /tmp/$archive /home/midas/html/elog/download/tar/elog-latest.tar.gz
cp /tmp/$archive /usr/src/redhat/SOURCES/elog-$version.tar.gz
cp -f doc/ChangeLog /home/midas/html/elog/download/ChangeLog
rm /tmp/$archive

# building RPMs
rm -f /usr/src/redhat/RPMS/i386/*
rm -f /usr/src/redhat/SRPMS/*
rpmbuild -ba elog.spec
cp /usr/src/redhat/RPMS/i386/elog*rpm /home/midas/html/elog/download/RPMS/
cp /usr/src/redhat/RPMS/i386/elog-$version-$release.i386.rpm /home/midas/html/elog/download/RPMS/elog-latest.i386.rpm
cp /usr/src/redhat/SRPMS/elog*rpm /home/midas/html/elog/download/SRPMS/
cp /usr/src/redhat/SRPMS/elog-$version-$release.src.rpm /home/midas/html/elog/download/SRPMS/elog-latest.src.rpm



