#!/bin/csh
#Usage: build <version> <release>
#Build ELOG distribution

if ($#argv < 2) then
  echo "Usage: build <version> <release>"
  exit
endif
 
set version = $argv[1]
set release = $argv[2]
set dir = /tmp/elog-$version
set archive = elog-$version-$release.tar.gz

# create temporary directory
rm -Rf $dir
mkdir $dir
mkdir $dir/doc
mkdir $dir/src
mkdir $dir/man
mkdir $dir/contrib
mkdir $dir/scripts
mkdir $dir/resources
mkdir $dir/themes
mkdir $dir/themes/default
mkdir $dir/themes/default/icons
mkdir $dir/logbooks/
mkdir $dir/logbooks/demo
mkdir $dir/../mxml

# checkout files
echo Updating files...
svn up

# copy files to archive
cp src/*.c $dir/src
cp src/*.h $dir/src
cp ../mxml/*.c $dir/../mxml
cp ../mxml/*.h $dir/../mxml
cp Makefile $dir
cp elogd.cfg $dir/elogd.cfg
cp COPYING $dir
cp README $dir
cp elogd.init_template $dir

cp eloghelp_*.html $dir/resources
cp eloglang.* $dir/resources

cp doc/* $dir/doc
cp man/* $dir/man
cp contrib/* $dir/contrib
cp scripts/* $dir/scripts

cp themes/default/* $dir/themes/default
cp themes/default/icons/* $dir/themes/default/icons
cp logbooks/demo/* $dir/logbooks/demo

# create elog-x.xx.tar.gz file
echo Creating archive...
cd /tmp
tar -cvzf $archive elog-$version/ mxml/

# remove temporary files
rm -Rf $dir/../mxml
rm -Rf $dir

# transfer archive
cp /tmp/$archive ~/html/elog/download/tar/
cp /tmp/$archive ~/html/elog/download/tar/elog-latest.tar.gz
cp /tmp/$archive /usr/src/redhat/SOURCES/elog-$version.tar.gz
cd ~/elog
cp -f doc/ChangeLog ~/html/elog/download/ChangeLog
rm /tmp/$archive

# building RPMs
rm -f /usr/src/redhat/RPMS/i386/*
rm -f /usr/src/redhat/SRPMS/*
rpmbuild -ba elog.spec
cp /usr/src/redhat/RPMS/i386/elog*rpm ~/html/elog/download/RPMS/
cp /usr/src/redhat/RPMS/i386/elog-$version-$release.i386.rpm ~/html/elog/download/RPMS/elog-latest.i386.rpm
cp /usr/src/redhat/SRPMS/elog*rpm ~/html/elog/download/SRPMS/
cp /usr/src/redhat/SRPMS/elog-$version-$release.src.rpm ~/html/elog/download/SRPMS/elog-latest.src.rpm



