#!/bin/csh
#Usage: build [-n] <version> <release>
#Build ELOG distribution

if ($#argv < 2) then
  echo "Usage: build <version> <release>"
  exit
endif
 
set version = $argv[1]
set release = $argv[2]
set dir = /tmp/elog-$version
set archive = elog-$version-$release.tar.gz

perl -wapi.bak -e 's&^(Version:\s+).*$&${1}'"${version}"'&;s&^(Release:\s+).*$&${1}'"${release}"'&;' elog.spec

# create temporary directory
rm -Rf $dir
mkdir $dir
mkdir $dir/doc
mkdir $dir/src
mkdir $dir/mxml
mkdir $dir/man
mkdir $dir/contrib
mkdir $dir/scripts
mkdir $dir/scripts/ckeditor
mkdir $dir/resources
mkdir $dir/ssl
mkdir $dir/themes
mkdir $dir/themes/default
mkdir $dir/themes/default/icons
mkdir $dir/logbooks/
mkdir $dir/logbooks/demo
mkdir $dir/logbooks/demo/2001

# copy files to archive
unalias cp
cp -p src/*.c $dir/src
cp -p src/*.h $dir/src
cp -p mxml/*.c $dir/mxml
cp -p mxml/*.h $dir/mxml
cp -p Makefile $dir
cp -p elogd.cfg $dir/elogd.cfg
cp -p COPYING $dir
cp -p README $dir
cp -p elogd.init_template $dir
cp -p elogd.plist $dir

cp -p doc/* $dir/doc
cp -p man/* $dir/man
cp -p contrib/* $dir/contrib
cp -p -r scripts/* $dir/scripts
cp -p resources/* $dir/resources
cp -p ssl/* $dir/ssl

cp -p themes/default/* $dir/themes/default
cp -p themes/default/icons/* $dir/themes/default/icons
cp -p logbooks/demo/2001/011108a.log $dir/logbooks/demo/2001/

# create elog-x.xx.tar.gz file
echo Creating archive...
cd /tmp
tar -cvzf $archive elog-$version/ mxml/

# remove temporary files
rm -Rf $dir

# transfer archive
cp /tmp/$archive ~ritt/html/elog/download/tar/
cp /tmp/$archive ~ritt/html/elog/download/tar/elog-latest.tar.gz
cp /tmp/$archive /usr/src/redhat/SOURCES/elog-$version.tar.gz
cd ~ritt/elog
cp -f doc/ChangeLog ~ritt/html/elog/download/ChangeLog
rm -f /tmp/$archive

# building RPMs
rm -f /usr/src/redhat/RPMS/i386/*
rm -f /usr/src/redhat/SRPMS/*
rpmbuild -ba elog.spec || exit $?
cp /usr/src/redhat/RPMS/i386/elog*rpm ~ritt/html/elog/download/RPMS/
cp /usr/src/redhat/RPMS/i386/elog-$version-$release.i386.rpm ~ritt/html/elog/download/RPMS/elog-latest.i386.rpm
cp /usr/src/redhat/SRPMS/elog*rpm ~ritt/html/elog/download/SRPMS/
cp /usr/src/redhat/SRPMS/elog-$version-$release.src.rpm ~ritt/html/elog/download/SRPMS/elog-latest.src.rpm



